version: '3'

services:
  web:
    build: .
    container_name: gpw-web
    ports:
      - 9000:80
      - 34000:34000
      - 35729:35729 # livereload
    depends_on:
      - memcached
      - mysql
    volumes:
      - .:/var/www:delegated
      - .docker/web/php.ini:/etc/php/7.3/fpm/php.ini
      - .docker/web/nginx.conf:/etc/nginx/nginx.conf
      - .docker/web/gazelle.conf:/etc/nginx/sites-available/gazelle.conf
    environment:
      - ENV=development
      # These should match what you set for your mysql container below
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=password

  memcached:
    image: memcached:1.5-alpine
    container_name: gpw-memcached
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gpw-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=gazelle
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    ports:
      - 9001:80
  mysql:
    image: mariadb:10.3
    container_name: gpw-mysql
    ports:
      - 36000:3306
    volumes:
      - ./.docker/mysql/mysqld_sql_mode.cnf:/etc/mysql/conf.d/mysqld_sql_mode.cnf:delegated
      - ./.docker/data/mysql:/var/lib/mysql
      - ./gazelle.sql:/docker-entrypoint-initdb.d/gazelle.sql:ro
    environment:
      - MYSQL_DATABASE=gazelle
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=em%G9Lrey4^N

  sphinxsearch:
    # build: ./.docker/sphinxsearch
    image: registry.cn-chengdu.aliyuncs.com/gy1682005/gazelle_sphinx:v210317
    container_name: gpw-sphinxsearch
    depends_on:
      - mysql
      - web
    volumes:
      - ./.docker/data/sphinxsearch:/var/lib/sphinxsearch/data/
      - ./.docker/sphinxsearch/sphinx.conf:/var/lib/sphinxsearch/conf/sphinx.conf
    environment:
      # These should match what you set for your mysql container above
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=password
